// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM4HISiS8cwNj3zujN3L4GmQGe3Sc1h7c',
    appId: '1:187248474934:android:0a1149b02bf61881261197',
    messagingSenderId: '187248474934',
    projectId: 'waaqti-4real',
    databaseURL: 'https://waaqti-4real-default-rtdb.firebaseio.com',
    storageBucket: 'waaqti-4real.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmAuvZXeQVP0LREX14rgTxRW9srjuloHc',
    appId: '1:187248474934:ios:3c6b7a737d11a08e261197',
    messagingSenderId: '187248474934',
    projectId: 'waaqti-4real',
    databaseURL: 'https://waaqti-4real-default-rtdb.firebaseio.com',
    storageBucket: 'waaqti-4real.firebasestorage.app',
    iosBundleId: 'com.keynetik.waaqti',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrJ5I0j4_ihkwxwoPQ-HLVBPlg4SWsPb4',
    appId: '1:187248474934:web:5c40817b4b4ac360261197',
    messagingSenderId: '187248474934',
    projectId: 'waaqti-4real',
    authDomain: 'waaqti-4real.firebaseapp.com',
    databaseURL: 'https://waaqti-4real-default-rtdb.firebaseio.com',
    storageBucket: 'waaqti-4real.firebasestorage.app',
    measurementId: 'G-5TKHPTMMFH',
  );
}
